-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-13.5999994, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-12.8000002, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-13.5999994, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-12.8000002, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11.8000002, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11.8000002, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-13.0424299, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-12.5724325, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-12.1024351, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-11.6324377, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-13.0424299, 2.44999981, -6.22746658, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -6.83237696, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -7.61321974, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -8.394063, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-12.0446014, 2.44999981, -6.25939894, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.8549223, 2.44999981, -7.11295366, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.8549223, 2.44999981, -8.34586525, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.475565, 2.44999981, -7.11295366, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.475565, 2.44999981, -8.4407053, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
