-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-13.5999994, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-12.8000002, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-13.5999994, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-12.8000002, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11.8000002, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11, 1.90000439, -27.7999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11.8000002, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Hamburger"
local ohCFrame3 = CFrame.new(-11, 1.90000439, -27, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-13.0424299, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-12.5724325, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-12.1024351, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-11.6324377, 2.44999981, -5.75746918, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Tomato"
local ohCFrame3 = CFrame.new(-13.0424299, 2.44999981, -6.22746658, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -6.83237696, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -7.61321974, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Carrots"
local ohCFrame3 = CFrame.new(-12.6886997, 2.44999981, -8.394063, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-12.0446014, 2.44999981, -6.25939894, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.8549223, 2.44999981, -7.11295366, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.8549223, 2.44999981, -8.34586525, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.475565, 2.44999981, -7.11295366, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Cucumber"
local ohCFrame3 = CFrame.new(-11.475565, 2.44999981, -8.4407053, 1.19248806e-08, 0, -1, 0, 1, 0, 1, 0, 1.19248806e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -28.1399994, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -28, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.8600006, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.7199993, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.5799999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.4400005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.2999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.1599998, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -27.0200005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-22.6100006, 2.99744725, -26.8799992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -28.1399994, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -28, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.8600006, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.7199993, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.5799999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.4400005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.2999992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.1599998, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -27.0200005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "PlaceProduct"
local ohString2 = "Bubble Gum"
local ohCFrame3 = CFrame.new(-21.8400002, 2.99744725, -26.8799992, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-18.1124992, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-18.1124992, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-19.1625004, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-19.1625004, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-20.2124996, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-20.2124996, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-21.2624989, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-21.2624989, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-22.3125, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-22.3125, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-23.3624992, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-23.3624992, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-24.4125004, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-24.4125004, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-25.4624996, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-25.4624996, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-25.4624996, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-26.5124989, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-26.5124989, 0.797447324, -27.8249989, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Instant Noodles"
local ohCFrame3 = CFrame.new(-18.1124992, 0.797447324, -26.7749996, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-17.8398228, 2.99744725, -27.8747234, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.2114868, 2.99744725, -27.8747234, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.583149, 2.99744725, -27.8747234, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.954813, 2.99744725, -27.8747234, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-17.8398228, 2.99744725, -26.9455662, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.2114868, 2.99744725, -26.9455662, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.583149, 2.99744725, -26.9455662, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-18.954813, 2.99744725, -26.9455662, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-19.3264751, 2.99744725, -27.8747234, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Candy Bar"
local ohCFrame3 = CFrame.new(-19.3264751, 2.99744725, -26.9455662, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-29.2678299, 0.797447324, -25.08671, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-28.2840366, 0.797447324, -25.08671, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-29.2678299, 0.797447324, -24.1029186, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-28.2840366, 0.797447324, -24.1029186, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-29.2678299, 0.797447324, -23.1191254, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-28.2840366, 0.797447324, -23.1191254, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-29.2678299, 0.797447324, -22.135334, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-28.2840366, 0.797447324, -22.135334, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-29.2678299, 0.797447324, -21.1515408, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Bread Bun"
local ohCFrame3 = CFrame.new(-28.2840366, 0.797447324, -21.1515408, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-26.4963341, 2.99744725, -28.1449947, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-26.4963341, 2.99744725, -27.6739502, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-26.4963341, 2.99744725, -27.2029037, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-26.4963341, 2.99340677, -26.7318573, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-24.7299118, 2.99744725, -28.1449947, -1, 0, -8.74227766e-08, 0, 1, 0, 8.74227766e-08, 0, -1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-24.7299118, 2.99744725, -27.6739502, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-24.7299118, 2.99744725, -27.2029037, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-24.7299118, 2.99744725, -26.7318573, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-23.6700592, 2.99744725, -27.438427, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Cookies"
local ohCFrame3 = CFrame.new(-23.1990128, 2.99744725, -27.438427, -4.37113883e-08, 0, 1, 0, 1, 0, -1, 0, -4.37113883e-08)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Soda"
local ohCFrame3 = CFrame.new(-29.0124989, 2.53234053, -1.92499995, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Soda"
local ohCFrame3 = CFrame.new(-29.0124989, 2.53234053, -2.4749999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Soda"
local ohCFrame3 = CFrame.new(-29.0124989, 2.53234053, -3.02499986, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Soda"
local ohCFrame3 = CFrame.new(-29.0124989, 2.53234053, -3.57500005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Generic Soda"
local ohCFrame3 = CFrame.new(-28.4624996, 2.53234053, -1.92499995, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Water"
local ohCFrame3 = CFrame.new(-28.4624996, 2.53234053, -2.4749999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Water"
local ohCFrame3 = CFrame.new(-28.4624996, 2.53234053, -3.02499986, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Water"
local ohCFrame3 = CFrame.new(-28.4624996, 2.53234053, -3.57500005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Water"
local ohCFrame3 = CFrame.new(-27.9125004, 2.53234053, -2.4749999, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Water"
local ohCFrame3 = CFrame.new(-27.9125004, 2.53234053, -3.02499986, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-29.0875015, 0.532341719, -1.95000005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-29.0875015, 0.532341719, -2.60000014, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-29.0875015, 0.532341719, -3.25, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-28.4375, 0.532341719, -1.95000005, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-28.4375, 0.532341719, -2.60000014, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

local ohString1 = "PlaceProduct"
local ohString2 = "Milk"
local ohCFrame3 = CFrame.new(-28.4375, 0.532341719, -3.25, 1, 0, 0, 0, 1, 0, 0, 0, 1)

game:GetService("ReplicatedStorage").Remote:FireServer(ohString1, ohString2, ohCFrame3)

loadstring(game:HttpGet(('https://raw.githubusercontent.com/Averymoistboi/InstaplaceACX/main/XCC'),true))()